### ISSUE TITLE
Deleting a PV doesn't remove it from Packet.

### ISSUE THREAD

**Issue by clanstyles** [packethost/csi-packet#46]
Deleting a PV doesn't remove it from your volumes at packet. Additionally, it doesn't unmount it from the  node and  Packet wont always let you delete the volume by hand without it being detached.

**Comment by clanstyles** [comment]
Nope! Doesn't work for me. Check the sample cluster I provided. The volume is still attached on the cluster after it was deleted. I have to manually unmount it and deleted it from the Packet portal.

**Comment by deitch** [comment]
Can we chat on slack? Once we figure it out, we can report and fix it here, but this kind of "pair debugging" is a little harder to do on an issue. Good to sync real time.

**Comment by deitch** [comment]
Also, I did just run a completely clean install and ran the `demo-pod.yml`, then deleted it. The pod itself goes away almost instantaneously, as does the `pvc`. The `pv` itself is cleaned up by Kubernetes and causes the volume to disappear, but it does take a bit of time (in my tests up to about a minute). I had the same process repeated over and over again, same results, all good.

If we can slack, let's run through it together and see if we can narrow down the issue.

**Comment by clanstyles** [comment]
This seems fixed. #53 contains a new edge case.
