### ISSUE TITLE
422 Storage cluster can't be blank

### ISSUE THREAD

**Issue by ashleyschuett** [packethost/csi-packet#6]
I'm trying to create a pvc using the `demo-deployment.yaml` but am getting a 422 error when the API tries to create the storage volume. Any insight into what's going wrong? The only info I can find in the api docs is `unprocessable entity`. 

```
  Normal   ExternalProvisioning  1m (x25 over 4m)  persistentvolume-controller                                              waiting for a volume to be created, either by external provisioner "csi-packet" or manually created by system administrator
  Normal   Provisioning          41s (x9 over 4m)  csi-packet csi-packet-controller-0 4e55449d-8c3f-11e8-a4e0-d23029befa80  External provisioner is provisioning volume for claim "default/podpvc"
  Warning  ProvisioningFailed    41s (x9 over 4m)  csi-packet csi-packet-controller-0 4e55449d-8c3f-11e8-a4e0-d23029befa80  Failed to provision volume with StorageClass "csi-packet-standard": rpc error: code = Unknown desc = POST https://api.packet.net/projects/$PROJECT_ID/storage: 422 Storage cluster can't be blank
```

The logs from the csi-external-provisioner are 

```
I0720 17:19:56.010046       1 controller.go:1167] scheduleOperation[provision-default/podpvc[c6e7fd43-8c3f-11e8-999f-ac1f6b2c9fca]]
E0720 17:19:56.010074       1 controller.go:1174] Error scheduling operaion "provision-default/podpvc[c6e7fd43-8c3f-11e8-999f-ac1f6b2c9fca]": Failed to create operation with name "provision-default/podpvc[c6e7fd43-8c3f-11e8-999f-ac1f6b2c9fca]". An operation with that name failed at 2018-07-20 17:18:26.810350719 +0000 UTC m=+695.089414279. No retries permitted until 2018-07-20 17:20:28.810350719 +0000 UTC m=+817.089414279 (2m2s). Last error: "rpc error: code = Unknown desc = POST https://api.packet.net/projects/$PROJECT_ID/storage: 422 Storage cluster can't be blank ".
```

**Comment by ntfrnzn** [comment]
@ashleyschuett this `POST https://api.packet.net/projects/$PROJECT_ID/storage` looks a little strange, can you check the contents of `cloud-sa` secret and make sure the project id is set correctly?  https://github.com/packethost/csi-packet/pull/3 will be merged soon and has newer versions of the CSI components. It also makes improvements to log output.

**Comment by ashleyschuett** [comment]
I'm using the new deployment yaml with the 0.0.3 changes and am still getting the same errors. The urls I posted with `$PROJECT_ID` was just me redacting the project it. It is using the correct id from my secret that matches the project id of my account. 

Is there something I need to create on packet through the UI for this to work? My understanding was that the controller takes care of creating everything. 

I applied the secret, then the setup.yaml, node.yaml, and controller.yaml. To test I was using the deployment-demo.yaml. But the podpvc stays in a state of pending due to the storage not being created by the controller.

**Comment by ashleyschuett** [comment]
Figured out the error was because my cluster was running in a facility that storage does not support.

**Comment by jacobsmith928** [comment]
@ashleyschuett would you expect different / clearer errors from the API or the CSI in this case?

**Comment by ashleyschuett** [comment]
Yes I think a different error would make it more clear.  The current error of `422 Storage cluster can't be blank` makes me think that I need to create a storage cluster in my account, which obviously isn't an option. Instead if the error message read something more along the lines of `Storage is not supported in your devices facility` or something along those lines it would be more clear. It's could be an error that comes from the controller on start up when getting the facility, or comes from the API, either would be helpful.

**Comment by mberrueta** [comment]
@ashleyschuett It make sense, I will add a ticket to check and change the error message. 

Thanks in advance
