### ISSUE TITLE
Update CSI Docs and Demo Deployment

### ISSUE THREAD

**Issue by enkelprifti98** [packethost/csi-packet#62]
Some parts of the doc need to be updated such as:

> Packet CSI version v0.0.2 supports Kubernetes version >=v1.10

The  `--allow-privileged=true` flag doesn't seem to be supported by the kubelet anymore but I was able to deploy the CSI driver without that requirement as mentioned in the docs.

The `demo-deployment.yaml` file doesn't work properly when you try to deploy it. It says the following:

`error: unable to recognize "demo-deployment.yaml": no matches for kind "Deployment" in version "v1beta1"`

It would also be helpful to have a sample deployment file for a PersistentVolume. All the demos as of now use PVCs.

**Comment by deitch** [comment]
> The demo-deployment.yaml file doesn't work properly when you try to deploy it. It says the following:
> error: unable to recognize "demo-deployment.yaml": no matches for kind "Deployment" in version "v1beta1"

Yes, good point. `Deployment` has been `apps/v1` for quite some time, just supported the old `extensions/v1beta1`, which finally was deprecated. No reason not to change it.

**Comment by deitch** [comment]
See #63 for the first issue

**Comment by deitch** [comment]
> It would also be helpful to have a sample deployment file for a PersistentVolume. All the demos as of now use PVCs

Yes. And I saw your comments in Slack. Please open a separate issue for this so we can track each separately with their detailed comments and have separate PRs to fix.

**Comment by enkelprifti98** [comment]
Thanks Avi, I opened a new issue for the PV sample. Check #64 .

**Comment by scottrobertson** [comment]
Just been caught out by the `allow-privileged` not being used on kubelet too.

**Comment by displague** [comment]
Thanks for the issue and thanks to everyone that contributed to the conversation.

I'm closing this as 'Will not fix' - see #103 (Equinix Metal Block Storage from Datera is EOL).
