### ISSUE TITLE
iscsiadmin logout error when deleting kubernetes pod, pvc

### ISSUE THREAD

**Issue by ntfrnzn** [packethost/csi-packet#7]
During a routine test to create and remove a pod and persistent volume claim, the volume remained in use on the host.  The specific error logged in the node packet-driver was:

```
{
  "args": "--mode node --portal 10.144.144.211 --targetname iqn.2013-05.com.daterainc:tc:01:sn:fa5a782b6ac6b5a9 --logout",
  "command": "iscsiadm",
  "error": "exit status 9",
  "level": "error",
  "msg": "Error",
  "out": "iscsiadm: Could not logout of [sid: 1, target: iqn.2013-05.com.daterainc:tc:01:sn:fa5a782b6ac6b5a9, portal: 10.144.144.211,3260].\niscsiadm: initiator reported error (9 - internal error)\niscsiadm: Could not logout of all requested sessions\nLogging out of session [sid: 1, target: iqn.2013-05.com.daterainc:tc:01:sn:fa5a782b6ac6b5a9, portal: 10.144.144.211,3260]\n",
  "time": "2018-07-24T18:43:12Z"
}
```
The error was reproducible when logging into the host and running the iscsiadm logout command directly.  The host was running coreos, and kubernetes 1.10.5, created through stackpoint.io.  
`iscsiadm -m session` confirmed that the portal and iqn were correct, but the logout command failed.

After restarting, `# systemctl restart iscsid` the logout succeeded. 

I'm not sure how the csi driver can or should handle errors from iscsiadm.  Manually ssh-ing to the host is not ok.

**Comment by deitch** [comment]
yes, manually _definitely_ is not ok! We finally cleaned up a huge amount on the CSI, so will be looking into this as well. My attempts to reproduce with the latest build fail. Can I ask you to attempt to recreate after the latest merges are in? I will be happy to flag here.

Thanks

**Comment by ntfrnzn** [comment]
Sorry, I don't have access to a packet/csi system any longer. Glad to hear that you've made improvements and cleaned things up!

**Comment by deitch** [comment]
In that case, given that my understanding is that we have addressed these, I am going to close the issue. If it recurs, we can open a new issue.
