### ISSUE TITLE
CSI driver crash/looping

### ISSUE THREAD

**Issue by DGollings** [packethost/csi-packet#73]
Steps to reproduce:
terraform apply [kubernetes-bgp](https://github.com/packet-labs/kubernetes-bgp)
(tested with kubernetes 1.15.3 and 1.16.3, set via .tfvars)

log into master node

`kubectl -n kube-system apply -f secret.yaml` (with newly generated project and valid api key)
`kubectl -n kube-system apply -f packet-ccm-deployment-v1.0.0.yaml`
`kubectl -n kube-system apply -f setup.yaml`
`kubectl -n kube-system apply -f node.yaml`
`kubectl -n kube-system apply -f controller.yaml`

Results in both the controller and csi-node crashing/looping

kubectl -n kube-system logs csi-node-svr7f packet-driver
```
{"level":"info","msg":"started","time":"2019-12-12T12:33:36Z","version":"834aea2"}
Error: required flag(s) "nodeid" not set
```

kubectl -n kube-system logs csi-node-svr7f csi-driver-registrar  
```
I1212 12:33:08.047106       1 main.go:111] Version: v1.0.1-0-g27703026
I1212 12:33:08.047220       1 main.go:118] Attempting to open a gRPC connection with: "/csi/csi.sock"
I1212 12:33:08.047248       1 connection.go:69] Connecting to /csi/csi.sock
I1212 12:33:08.047822       1 connection.go:96] Still trying, connection is CONNECTING
I1212 12:33:08.048329       1 connection.go:96] Still trying, connection is TRANSIENT_FAILURE
I1212 12:33:09.048215       1 connection.go:96] Still trying, connection is TRANSIENT_FAILURE
I1212 12:33:10.090102       1 connection.go:96] Still trying, connection is CONNECTING
I1212 12:33:10.090151       1 connection.go:96] Still trying, connection is TRANSIENT_FAILURE
(...)
I1212 12:34:08.047488       1 connection.go:89] Connection timed out
I1212 12:34:08.047542       1 main.go:126] Calling CSI driver to discover driver name.
I1212 12:34:08.047567       1 connection.go:137] GRPC call: /csi.v1.Identity/GetPluginInfo
I1212 12:34:08.047585       1 connection.go:138] GRPC request: {}
I1212 12:34:08.049640       1 connection.go:140] GRPC response: {}
I1212 12:34:08.052655       1 connection.go:141] GRPC error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
E1212 12:34:08.052755       1 main.go:131] rpc error: code = Unavailable desc = all SubConns are in TransientFailure
```

kubectl -n kube-system logs csi-packet-controller-0 packet-driver
```
{"level":"info","msg":"started","time":"2019-12-12T12:33:53Z","version":"834aea2"}
Error: required flag(s) "nodeid" not set
Usage:
  Packet [flags]

Flags:
      --config string     path to provider config file
      --endpoint string   CSI endpoint
  -h, --help              help for Packet
      --nodeid string     node id
```

kubectl -n kube-system logs packet-cloud-controller-manager-fc89f8979-75t75

```
Flag --allow-untagged-cloud has been deprecated, This flag is deprecated and will be removed in a future release. A cluster-id will be required on cloud instances.
Flag --allow-untagged-cloud has been deprecated, This flag is deprecated and will be removed in a future release. A cluster-id will be required on cloud instances.
Flag --allow-untagged-cloud has been deprecated, This flag is deprecated and will be removed in a future release. A cluster-id will be required on cloud instances.
I1212 12:27:29.354543       1 serving.go:319] Generated self-signed cert in-memory
W1212 12:27:31.330062       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1212 12:27:31.338628       1 controllermanager.go:117] Version: v0.0.0-master+$Format:%h$
W1212 12:27:31.338714       1 controllermanager.go:129] detected a cluster without a ClusterID.  A ClusterID will be required in the future.  Please tag your cluster to avoid any future issues
I1212 12:27:31.340162       1 secure_serving.go:116] Serving securely on [::]:10258
I1212 12:27:31.342655       1 node_controller.go:71] Sending events to api server.
I1212 12:27:31.342773       1 controllermanager.go:244] Started "cloud-node"
I1212 12:27:31.345330       1 node_lifecycle_controller.go:77] Sending events to api server
I1212 12:27:31.345428       1 controllermanager.go:244] Started "cloud-node-lifecycle"
E1212 12:27:31.348005       1 core.go:80] Failed to start service controller: the cloud provider does not support external load balancers
W1212 12:27:31.348038       1 controllermanager.go:241] Skipping "service"
I1212 12:27:31.348057       1 core.go:91] Will not configure cloud provider routes for allocate-node-cidrs: false, configure-cloud-routes: true.
W1212 12:27:31.348074       1 controllermanager.go:241] Skipping "route"
E1212 12:27:32.865807       1 node_controller.go:140] unexpected providerID format: 4fc34b43-8e6a-4035-b3eb-7b5728837f69, format should be: packet://device-id
E1212 12:27:34.103345       1 node_controller.go:140] unexpected providerID format: 485bcd20-fce0-4551-bee0-2c4b58f2f65f, format should be: packet://device-id
E1212 12:32:35.486082       1 node_controller.go:140] unexpected providerID format: 4fc34b43-8e6a-4035-b3eb-7b5728837f69, format should be: packet://device-id
E1212 12:32:36.619198       1 node_controller.go:140] unexpected providerID format: 485bcd20-fce0-4551-bee0-2c4b58f2f65f, format should be: packet://device-id
E1212 12:37:38.026827       1 node_controller.go:140] unexpected providerID format: 4fc34b43-8e6a-4035-b3eb-7b5728837f69, format should be: packet://device-id
E1212 12:37:39.041971       1 node_controller.go:140] unexpected providerID format: 485bcd20-fce0-4551-bee0-2c4b58f2f65f, format should be: packet://device-id
```

There are some leads I could try diving into myself, in particular node_controller.go:140 unexpected  format, but before I do so I figured I'd ask:

Bug or feature? :)

**Comment by deitch** [comment]
Thanks for raising this. Might have an issue in the manifests. Will take a look.

**Comment by deitch** [comment]
Hi @DGollings. This is a mismatch between the manifest and the version. The current released version 1.0.0 has a requirement that `nodeid` be set. This created all sorts of complexities, especially as the Kubernetes-understood node ID (the only thing you can pass down via the downward API, and normally is the hostname) is distinct from the internal Packet ID (which is a UUID). This sort of is fixed by the CCM, but we really shouldn't depend on that.

There are several PRs that have been merged into master, and several more in place, that solve this issue and several others. We had some issues with CI - GitHub Actions and accounts, DM me on Packet Slack if you really want to know the gory details - which have prevented our ability to push out a v1.0.1 which contains all of the fixes. 

On the other hand, the manifests in `master` are up to date with the latest merged code in master, i.e. ahead of the 1.0.0 release. We probably should have versioned the manifests; something for the future.

In any case, I believe we are close to getting CI (and therefore releases) fixed, will merge in those outstanding PRs and cut a new release, which will resolve all of this.

I will leave this issue open for the next few days as this all falls into place.

**Comment by DGollings** [comment]
> This sort of is fixed by the CCM, but we really shouldn't depend on that.

Ah, I kind of assumed that was the (only) reason to use/enable/install packet ccm, because what else does it do?

Thanks either way, sounds like you're pretty close to fixing this. 

I've been wanting to test something on packet.net kubernetes, does release 0.4.0 work in the meantime? (I realize I could simply try it out instead of asking :))

And I'll happily test 1.0.1 when it's out. Glad I took the time to raise this issue.

**Comment by deitch** [comment]
> because what else does it do?

I haven't had the chance to see if kubelet does a better job with the ID when ccm is in place, but ccm itself does some unexpected things when it gets and sends the provider instance ID. CCM doesn't actually have a `DaemonSet`, i.e. doesn't run on every node, just has a `Deployment` (you can use a `StatefulSet`) so it just runs one copy, while CSI has one instance per node via a `DaemonSet`.

> you're pretty close to fixing this

We are indeed. As a matter of fact, CI just cleared. Can you use the latest commit in your manifest to see? We still have an open issue around deleting volumes, which shows up when you reuse them; we are working on that.

The latest commit is `11ded09c9d7c858c8adc9cc276e78eeabc4ac2ce`, or, if you prefer, `packethost/csi-packet:11ded09c9d7c858c8adc9cc276e78eeabc4ac2ce`. It will go into `v1.0.1` shortly.

> Glad I took the time to raise this issue

As are we! Thank you.

**Comment by DGollings** [comment]
I terraform applied  kubernets-bgp with kubernetes 1.16.3 again, applied all the yamls except for CCM (seeing as there doesn't seem to be a reason to) and can confirm that commit 11ded09 works. 

Well, it worked for the one block device I managed to request before hitting my project limit of one (1) volume. Waiting for that limit to be raised so I can start performance testing this solution with cockroachdb.

Thanks :)

**Comment by deitch** [comment]
That is very good! We are working through a backend timing issue (being bare metal means hardware issues get exposed), and then I will cut a new release. As it was all bugfixes, probably 1.0.1. 

> my project limit of one (1) volume

DM me a link to the project page on Packet's community Slack, and I will see if I can get someone to raise it for that project. 

> I can start performance testing this solution with cockroachdb.

Oh, now _that_ sounds interesting. Let's talk on Slack.

**Comment by deitch** [comment]
In any case, if this issue is fixed, can we close it out?

**Comment by DGollings** [comment]
of course, closed

**Comment by DGollings** [comment]
(@deitch  https://slack.packet.net/ times out, do you have a direct link?)

**Comment by deitch** [comment]
Huh. I will raise an issue immediately.

**Comment by deitch** [comment]
People looking into it.

**Comment by deitch** [comment]
I just found out it was fixed @DGollings . Please try again.
