### ISSUE TITLE
statefulset pod recovery is inconsistent

### ISSUE THREAD

**Issue by ntfrnzn** [packethost/csi-packet#8]
A very specific but reproducible case. First, create a statefulset with dynamic volumes to create and attach a volume to each pod. Delete one of pod in the statefulset, and see it rescheduled on the same node.  It will frequently remain in a pending state, unable to remount the persistent volume.  

Looking closely, the csi driver is calling NodeUnstageVolume and NodeUnpublishVolume, but there are no grpc calls to the controller to unpublish and publish the volume to the host.  Often, simply deleting the (pending) pod again after some minutes will result in the correct grpc calls, and thus getting the pod to restart.

It will be important to test this again on kubernetes v1.11

**Comment by ntfrnzn** [comment]
Testing now with 1.11.1 gives the same results, and it seems to be something cached (or not) by kubelet. After upping the verbosity on the kubelet logs ,
```
kubelet[14151]: I0726 16:47:45.032201   14151 csi_attacher.go:125] kubernetes.io/csi: probing for updates from CSI driver for [attachment.ID=]
kubelet[14151]: I0726 16:47:45.032221   14151 csi_attacher.go:134] kubernetes.io/csi: probing VolumeAttachment [id=]
kubelet[14151]: I0726 16:47:45.032248   14151 request.go:641] Error in request: resource name may not be empty
kubelet[14151]: E0726 16:47:45.032280   14151 csi_attacher.go:137] kubernetes.io/csi: attacher.WaitForAttach failed for volume [2bae4c4f-6e70-4923-b3e4-cf3fbd02811a] (will continue to try): resource name may not be empty
```
from *VolumeAttachment [id=]*, WaitForAttach is being called with an empty attachId, which comes from an empty volumeToMount.DevicePath, which is called in from MountVolume

```
operationExecutor.MountVolume started for volume "pvc-82f771dc90ee11e8" (UniqueName: "kubernetes.io/csi/net.packet.csi^2bae4c4f-6e70-4923-b3e4-cf3fbd02811a") pod "stateful-nginx-1" (UID: "5f239f43-90f9-11e8-b78d-0cc47ab21512")
```
This leads back to code in kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go, where it seems that the devicePath is being set to an empty string.

Restarting kubelet on the node will properly read values and trigger the csi calls to mount the volume

**Comment by deitch** [comment]
As far as I can tell @ntfrnzn , the issue was an underlying kubelet issue that was resolved with [this PR](https://github.com/kubernetes/kubernetes/pull/71074), good for Kubernetes versions as of:

* 1.11 >= 1.11.7
* 1.11 >= 1.12.5
* 1.3+

Is this correct? Can you verify, or give us steps to verify (although I think we know what it is based on [this](https://github.com/kubernetes/kubernetes/issues/67342) but always worth asking)?

**Comment by deitch** [comment]
I am closing this out, as no response after a month+. If this issue recurs with the latest releases, please open a new issue.
